// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qimeswwszpwbwtmckpzu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFpbWVzd3dzenB3Ynd0bWNrcHp1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk3MTk2NDgsImV4cCI6MjA2NTI5NTY0OH0.Js5DVfC1YzZwbpiu6fcq1-Iam3x89soKjJ-LkEs4Vow";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);